import {AUTH_ISSUER} from './authorization-policy.ts';
export const GITHUB_CALLBACK=AUTH_ISSUER+'/github/callback';
export function githubAuthorizationUrl(clientId:string,state:string,challenge:string):string {
 const url=new URL('https://github.com/login/oauth/authorize');
 for(const [key,value] of Object.entries({client_id:clientId,redirect_uri:GITHUB_CALLBACK,state,code_challenge:challenge,code_challenge_method:'S256'}))url.searchParams.set(key,value);
 return url.href;
}
export async function exchangeGithubCode(clientId:string,clientSecret:string,code:string,verifier:string,fetcher:typeof fetch=fetch):Promise<string>{
 if(!clientId||!clientSecret||!code||code.length>4096||!/^[-A-Za-z0-9_.~]{43,128}$/.test(verifier))throw new Error('identity_exchange_failed');
 let response:Response;
 try{response=await fetcher('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,code,redirect_uri:GITHUB_CALLBACK,code_verifier:verifier}),redirect:'error',signal:AbortSignal.timeout(10000)});}catch{throw new Error('identity_exchange_failed');}
 if(!response.ok)throw new Error('identity_exchange_failed');
 const raw=await response.text();if(raw.length>16384)throw new Error('identity_exchange_failed');
 let value:unknown;try{value=JSON.parse(raw);}catch{throw new Error('identity_exchange_failed');}
 if(!value||typeof value!=='object'||!('access_token' in value)||typeof value.access_token!=='string'||!value.access_token||value.access_token.length>4096||/[\r\n]/.test(value.access_token))throw new Error('identity_exchange_failed');
 return value.access_token;
}
export function escapeHtml(value:string):string {return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
const PAGE_STYLE = `
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#0b1020;color:#edf0f7}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:32px 20px;background:radial-gradient(ellipse at top,#26203e 0,#0b1020 65%)}main{width:100%;max-width:560px;background:#121827;border:1px solid #30364a;border-radius:20px;padding:32px;box-shadow:0 24px 80px #0005}.brand{display:flex;align-items:center;gap:12px;margin-bottom:28px}.mark{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:#9a6bff;color:#fff;font-weight:800;font-size:13px}.brand strong{font-size:17px}.byline{display:block;color:#a7b0c4;font-size:12px;margin-top:3px}h1{font-size:28px;line-height:1.2;letter-spacing:-.6px;margin:0 0 12px}p{color:#b9c2d6;line-height:1.6;margin:12px 0}.identity{background:#0e1422;border:1px solid #30364a;border-radius:12px;padding:14px 16px;margin:22px 0}dl{margin:0;display:grid;grid-template-columns:110px 1fr;gap:10px;font-size:14px}dt{color:#a7b0c4}dd{margin:0;overflow-wrap:anywhere}.note{font-size:13px}.permissions{padding-left:20px;color:#d9dfed;line-height:1.6}.options{display:grid;gap:12px;margin:18px 0}label{display:flex;gap:10px;align-items:flex-start;line-height:1.5}select{font:inherit;padding:10px;border:1px solid #48516a;border-radius:8px;background:#0e1422;color:#edf0f7;max-width:100%}input[type=checkbox]{accent-color:#9a6bff;width:18px;height:18px;margin-top:3px;flex-shrink:0}.actions{display:flex;gap:10px;margin-top:24px}button,.button{font:inherit;font-weight:650;padding:12px 18px;border-radius:10px;border:1px solid #48516a;cursor:pointer;color:#edf0f7;background:#1a2235;text-decoration:none}button[name=decision][value=allow],.primary{background:#9260ef;border-color:#a87bf9;flex:1}button:focus-visible,a:focus-visible{outline:3px solid #c7a7ff;outline-offset:3px}details{margin-top:22px;color:#a7b0c4;font-size:12px;overflow-wrap:anywhere}summary{cursor:pointer}code{color:#c4aaff}.footer{margin-top:22px;font-size:12px;color:#a7b0c4;border-top:1px solid #30364a;padding-top:16px}@media(max-width:480px){body{padding:16px}main{padding:24px 20px}h1{font-size:25px}dl{grid-template-columns:90px 1fr}.actions{flex-wrap:wrap}}
`;
export function renderAuthPage(title:string,content:string):string {
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>'+escapeHtml(title)+' · SuperLocalMemory</title><style>'+PAGE_STYLE+'</style></head><body><main><div class="brand"><span class="mark" aria-hidden="true">SLM</span><div><strong>SuperLocalMemory</strong><span class="byline">by Qualixar</span></div></div>'+content+'<p class="footer">Optional web connections. Your local SLM continues to work without sign-in.</p></main></body></html>';
}
export function renderConsentPage(handle:string,description:{clientName:string;redirectHostname:string;redirectIsLoopback:boolean;scope:string[];clientDomain?:string;profileId?:string}):string {
 const native=description.scope.length===1&&description.scope[0]==='slm:connect';
 const permissions=native?'<li>Link this computer and local profile to your SLM account.</li>':'<li>Allow this application to read approved memories from your selected profile.</li>';
 const options=(description.scope.includes('slm:write')?'<label><input type="checkbox" name="write" value="yes"> Allow saving memories</label>':'')+(description.scope.includes('slm:session')?'<label><input type="checkbox" name="session" value="yes"> Allow session tools</label>':'');
 return renderAuthPage(native?'Link this computer':'Connect your AI','<h1>'+(native?'Link this computer':'Connect your AI')+'</h1><p>Sign in with GitHub to '+(native?'connect your local SLM profile. Your database stays on this computer.':'choose your SLM connection and approve access for this application.')+'</p><div class="identity"><dl><dt>Application</dt><dd>'+escapeHtml(description.clientName)+'</dd>'+(description.profileId?'<dt>Local profile</dt><dd>'+escapeHtml(description.profileId)+'</dd>':'')+'<dt>Returns to</dt><dd>'+escapeHtml(description.redirectHostname)+(description.redirectIsLoopback?' (this computer)':'')+'</dd></dl></div><p class="note">'+(description.clientDomain?'Client domain: '+escapeHtml(description.clientDomain):'The application name is supplied by the client.')+'</p><h2>What you are approving</h2><ul class="permissions">'+permissions+'</ul><p class="note">'+(native?'Only continue if you started this connection in your SLM dashboard. AI memory access requires its own approval.':'Approved memory results will be shared with this application. Saving and session tools remain off unless you select them below.')+'</p><form method="post" action="/consent"><input type="hidden" name="handle" value="'+escapeHtml(handle)+'"><div class="options">'+options+'</div><div class="actions"><button name="decision" value="allow">Sign in with GitHub</button><button name="decision" value="deny">Cancel</button></div></form><details><summary>Technical permissions</summary><p>'+description.scope.map(escapeHtml).join(', ')+'</p></details>');
}
export function renderAuthFailure(error:string):string {
 return renderAuthPage('Sign-in needs another attempt','<h1>Sign-in needs another attempt</h1><p>This connection request has expired, was already used, or could not be verified. Return to your dashboard to check the connection status and start a fresh sign-in request.</p><div class="identity"><strong>Return to your SLM dashboard</strong><p>Close this page. If the connection is still pending, cancel that request, then select <strong>Link this computer with GitHub</strong> to start again.</p></div><p>If GitHub asks you to log in, complete login on github.com. Do not enter your GitHub password on this page.</p><details><summary>Support information</summary><p>Code: <code>'+escapeHtml(error)+'</code></p></details>');
}
