import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
const {ConnectorSupervisor}=await import('../src/connector-supervisor.ts').catch(()=>({}));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
class Socket extends EventEmitter {sent=[];dead=false;bufferedAmount=0;send(x){this.sent.push(x);}terminate(){if(!this.dead){this.dead=true;this.emit('close');}}}
const enrollment=()=>({endpoint:'wss://connect.superlocalmemory.com/connector',deviceToken:'a'.repeat(40),expiresAt:Date.now()+60000,origin:'http://127.0.0.1:9999/mcp/',originHeaders:{'X-Install-Token':'synthetic'},codecOptions:{requestParamHeaders:[]}});
function setup(overrides={}){const sockets=[],states=[];const supervisor=new ConnectorSupervisor({enabled:true,loadEnrollment:async()=>enrollment(),dial:()=>{const socket=new Socket();sockets.push(socket);return socket;},onState:s=>states.push(s),retryMs:10,readyTimeoutMs:20,heartbeatMs:10000,...overrides});return{supervisor,sockets,states};}
test('supervisor implementation exists',()=>assert.equal(typeof ConnectorSupervisor,'function'));
test('remote is disabled by default',async()=>{let loads=0;const s=setup({enabled:false,loadEnrollment:async()=>{loads++;return enrollment();}});await s.supervisor.start();assert.equal(loads,0);assert.equal(s.sockets.length,0);assert.equal(s.states.at(-1),'disabled');});
test('duplicate start creates one socket and ready is needed for connected',async()=>{const s=setup();await Promise.all([s.supervisor.start(),s.supervisor.start()]);assert.equal(s.sockets.length,1);assert.ok(!s.states.includes('connected'));s.sockets[0].emit('message',Buffer.from('{"v":1,"kind":"ready","generation":1}'),false);await delay(1);assert.equal(s.states.at(-1),'connected');s.supervisor.stop();});
test('network loss reconnects and stop prevents subsequent reconnect',async()=>{const s=setup();await s.supervisor.start();s.sockets[0].emit('close');await delay(30);assert.ok(s.sockets.length>=2);s.supervisor.stop();const count=s.sockets.length;await delay(30);assert.equal(s.sockets.length,count);});
test('authorization rejection halts reconnect',async()=>{const s=setup();await s.supervisor.start();s.sockets[0].emit('unexpected-response',{}, {statusCode:403,resume(){}});await delay(30);assert.equal(s.sockets.length,1);assert.equal(s.states.at(-1),'authorization_required');s.supervisor.stop();});
test('stop fences asynchronous enrollment loading',async()=>{let finish;const s=setup({loadEnrollment:()=>new Promise(r=>{finish=r;})});const start=s.supervisor.start();s.supervisor.stop();finish(enrollment());await start;assert.equal(s.sockets.length,0);});
test('expired credential is not used to dial',async()=>{const s=setup({loadEnrollment:async()=>({...enrollment(),expiresAt:0})});await s.supervisor.start();assert.equal(s.sockets.length,0);assert.equal(s.states.at(-1),'authorization_required');s.supervisor.stop();});
test('missing ready handshake releases socket',async()=>{const s=setup();await s.supervisor.start();await delay(25);assert.equal(s.sockets[0].dead,true);s.supervisor.stop();});
test('credential loader errors are sanitized and require attention',async()=>{const s=setup({loadEnrollment:async()=>{throw new Error('SECRET');}});await s.supervisor.start();assert.equal(s.states.at(-1),'configuration_error');assert.ok(!JSON.stringify(s.states).includes('SECRET'));s.supervisor.stop();});
test('heartbeat closes an unresponsive socket',async()=>{const s=setup({heartbeatMs:5,readyTimeoutMs:100});await s.supervisor.start();s.sockets[0].emit('message',Buffer.from('{"v":1,"kind":"ready","generation":1}'),false);await delay(18);assert.ok(s.sockets[0].sent.includes('ping'));assert.equal(s.sockets[0].dead,true);s.supervisor.stop();});
test('binary frames terminate connection',async()=>{const s=setup();await s.supervisor.start();s.sockets[0].emit('message',Buffer.from('malformed'),true);assert.equal(s.sockets[0].dead,true);s.supervisor.stop();});
