import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const source=readFileSync(new URL('../../../src/superlocalmemory/ui/js/od-connections.js',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function setup(status={available:true,current_profile:'profile-a',hosts:['muse','chatgpt'],connections:[]},reply={state:'pending'}){
 const dom=new JSDOM('<!doctype html><div id="pane"></div>',{url:'http://127.0.0.1:8765',runScripts:'outside-only'});const calls=[];let fail=false;
 dom.window.slmFetch=async(path,init={})=>{calls.push({path,init});if(init.method==='POST'&&fail)throw new Error('synthetic transport error');return new Response(JSON.stringify(init.method==='POST'?reply:status),{status:200});};dom.window.eval(source);const card=dom.window.odCreateAiConnectionsCard();dom.window.document.getElementById('pane').append(card);await tick();await tick();return {dom,card,calls,setFail:v=>{fail=v;}};
}
function click(card,text){const btn=[...card.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(btn,'button '+text+' exists');btn.click();}
async function submit(f,optIn=true){click(f.card,'Add AI connection');const checkbox=f.card.querySelector('[data-remote-opt-in]');assert.ok(checkbox);checkbox.checked=optIn;f.card.querySelector('form').dispatchEvent(new f.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await tick();}
test('existing dashboard card exposes connection initiation without infrastructure fields',async()=>{const f=await setup();try{assert.match(f.card.textContent,/Connect your AI/);assert.ok(f.card.querySelector('button'));assert.equal(f.card.querySelector('input[type=password]'),null);assert.doesNotMatch(f.card.textContent,/API token|DNS record|terminal command/);}finally{f.dom.window.close();}});
test('rendering never enables remote access automatically',async()=>{const f=await setup();try{assert.equal(f.calls.filter(x=>x.init.method==='POST').length,0);assert.equal(f.calls[0].path,'/api/v3/connections/status');}finally{f.dom.window.close();}});
test('explicit UI consent and chosen host initiate through local authenticated fetch helper',async()=>{const f=await setup();try{await submit(f);const call=f.calls.find(x=>x.init.method==='POST');assert.ok(call);assert.equal(call.path,'/api/v3/connections/initiate');const body=JSON.parse(call.init.body);assert.equal(body.remote_opt_in,true);assert.equal(body.profile_id,'profile-a');assert.equal(body.host,'muse');assert.deepEqual(body.permissions,{read:true,write:false,correction:false,session:false});assert.ok(call.init.headers['Idempotency-Key']);assert.equal(call.init.credentials,'same-origin');}finally{f.dom.window.close();}});
test('absent consent blocks initiation',async()=>{const f=await setup();try{await submit(f,false);assert.equal(f.calls.filter(x=>x.init.method==='POST').length,0);}finally{f.dom.window.close();}});
test('unavailable backend disables initiation honestly',async()=>{const f=await setup({available:false,current_profile:'profile-a',hosts:['muse'],connections:[]});try{assert.ok([...f.card.querySelectorAll('button')].find(x=>x.textContent==='Add AI connection').disabled);assert.match(f.card.textContent,/unavailable/i);}finally{f.dom.window.close();}});
test('pending receipt never appears as connected',async()=>{const f=await setup();try{await submit(f);assert.match(f.card.textContent,/Waiting|requested|pending/i);assert.doesNotMatch(f.card.textContent,/Connected/);}finally{f.dom.window.close();}});
test('unsafe authorization links are never inserted',async()=>{for(const url of ['javascript:alert(1)','https://evil.example/authorize','https://name:pass@auth.superlocalmemory.com/authorize']){const f=await setup(undefined,{state:'pending',authorization_url:url});try{await submit(f);assert.equal(f.card.querySelector('a'),null);}finally{f.dom.window.close();}}});
test('approved sign-in link is exposed with safe new-window attributes',async()=>{const f=await setup(undefined,{state:'pending',authorization_url:'https://auth.superlocalmemory.com/authorize?state=synthetic'});try{await submit(f);const link=f.card.querySelector('a');assert.ok(link);assert.equal(link.rel,'noopener noreferrer');}finally{f.dom.window.close();}});
test('same uncertain request retry retains idempotency key',async()=>{const f=await setup();try{f.setFail(true);await submit(f);const form=f.card.querySelector('form');assert.ok(form);f.setFail(false);form.dispatchEvent(new f.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await tick();const posts=f.calls.filter(x=>x.init.method==='POST');assert.equal(posts.length,2);assert.equal(posts[0].init.headers['Idempotency-Key'],posts[1].init.headers['Idempotency-Key']);}finally{f.dom.window.close();}});
test('unverified connected status is not trusted',async()=>{const f=await setup({available:true,current_profile:'profile-a',hosts:['muse'],connections:[{host:'muse',state:'connected',verified:false}]});try{assert.doesNotMatch(f.card.textContent,/Connected/);}finally{f.dom.window.close();}});
