import test from 'node:test';
import assert from 'node:assert/strict';
import { createEnrollment, transitionEnrollment } from '../src/enrollment.ts';
const now = 1000;
function seed() { return { remoteOptIn: true, ownerId: 'owner-a', installationId: 'install-a', enrollmentId: 'enroll-a', profileId: 'profile-a', idempotencyKey: 'key-a', payloadDigest: 'a'.repeat(64), expiresAt: 2000 }; }
function record(status = 'requested') { const { remoteOptIn, ...s } = seed(); return { ...s, status, version: 1, connectorGeneration: 1 }; }
function context(r) { return { ownerId: r.ownerId, installationId: r.installationId, expectedVersion: r.version, connectorGeneration: r.connectorGeneration, now }; }
function denied(r, event, c, code) { assert.deepEqual(transitionEnrollment(r, event, c), { ok: false, code }); }
test('remote setup requires explicit UI opt-in', () => { assert.deepEqual(createEnrollment({ ...seed(), remoteOptIn: false }, 'owner-a', now), { ok: false, code: 'OPT_IN_REQUIRED' }); });
test('enrollment owner comes from verified login', () => { assert.deepEqual(createEnrollment(seed(), 'owner-b', now), { ok: false, code: 'OWNER_MISMATCH' }); });
test('new enrollment starts requested without enabling traffic', () => { const s = seed(); const before = JSON.stringify(s); const r = createEnrollment(s, 'owner-a', now); assert.equal(r.ok, true); assert.equal(r.enrollment.status, 'requested'); assert.equal(r.enrollment.version, 1); assert.equal(r.enrollment.connectorGeneration, 1); assert.equal('remoteOptIn' in r.enrollment, false); assert.equal(JSON.stringify(s), before); });
test('invalid or expired enrollment seed rejected', () => { for (const patch of [{ expiresAt: now }, { expiresAt: NaN }, { payloadDigest: 'not-a-digest' }, { installationId: '' }, { profileId: '' }]) assert.deepEqual(createEnrollment({ ...seed(), ...patch }, 'owner-a', now), { ok: false, code: 'INVALID_ENROLLMENT' }); });
test('ready requires all verification stages', () => { let r = record(); for (const event of ['authorize', 'start_provision', 'provisioned', 'connector_arrived', 'verified']) { const next = transitionEnrollment(r, event, context(r)); assert.equal(next.ok, true); assert.equal(next.enrollment.version, r.version + 1); r = next.enrollment; } assert.equal(r.status, 'ready'); });
test('provider success cannot skip origin verification', () => { const r = record('provisioning'); denied(r, 'verified', context(r), 'INVALID_TRANSITION'); });
test('foreign owner cannot advance enrollment', () => { const r = record(); denied(r, 'authorize', { ...context(r), ownerId: 'owner-b' }, 'BINDING_MISMATCH'); });
test('other installation cannot advance enrollment', () => { const r = record(); denied(r, 'authorize', { ...context(r), installationId: 'install-b' }, 'BINDING_MISMATCH'); });
test('stale record version rejected', () => { const r = record(); denied(r, 'authorize', { ...context(r), expectedVersion: 0 }, 'VERSION_CONFLICT'); });
test('stale connector generation rejected', () => { const r = record('verifying'); denied(r, 'verified', { ...context(r), connectorGeneration: 0 }, 'GENERATION_CONFLICT'); });
test('expired provisioning cannot become ready', () => { const r = record('verifying'); denied(r, 'verified', { ...context(r), now: r.expiresAt }, 'ENROLLMENT_EXPIRED'); });
test('cancel advances generation and prevents late callback revival', () => { const r = record('verifying'); const c = context(r); const cancel = transitionEnrollment(r, 'disconnect', c); assert.equal(cancel.ok, true); assert.equal(cancel.enrollment.status, 'disconnecting'); assert.equal(cancel.enrollment.connectorGeneration, 2); denied(cancel.enrollment, 'verified', { ...context(cancel.enrollment), connectorGeneration: 1 }, 'GENERATION_CONFLICT'); });
test('provider cleanup failure stays pending until acknowledged complete', () => { let r = record('disconnecting'); const failed = transitionEnrollment(r, 'cleanup_failed', context(r)); assert.equal(failed.ok, true); r = failed.enrollment; assert.equal(r.status, 'cleanup_pending'); const done = transitionEnrollment(r, 'cleanup_complete', context(r)); assert.equal(done.ok, true); assert.equal(done.enrollment.status, 'revoked'); });
test('expired enrollment still permits disconnect and cleanup', () => { let r = record('awaiting_connector'); let c = { ...context(r), now: 9999 }; const result = transitionEnrollment(r, 'disconnect', c); assert.equal(result.ok, true); r = result.enrollment; const done = transitionEnrollment(r, 'cleanup_complete', { ...context(r), now: 9999 }); assert.equal(done.ok, true); });
test('revoked enrollment cannot restart', () => { const r = record('revoked'); denied(r, 'start_provision', context(r), 'INVALID_TRANSITION'); });
test('retryable provider failure can resume provisioning', () => { const r = record('failed_retryable'); const next = transitionEnrollment(r, 'start_provision', context(r)); assert.equal(next.ok, true); assert.equal(next.enrollment.status, 'provisioning'); });
test('terminal failure can disconnect but cannot resume', () => { const r = record('failed_terminal'); denied(r, 'start_provision', context(r), 'INVALID_TRANSITION'); assert.equal(transitionEnrollment(r, 'disconnect', context(r)).ok, true); });
test('invalid clocks fail closed', () => { const r = record(); denied(r, 'authorize', { ...context(r), now: NaN }, 'INVALID_ENROLLMENT'); });
test('transition never mutates source record', () => { const r = Object.freeze(record()); const before = JSON.stringify(r); const next = transitionEnrollment(r, 'authorize', context(r)); assert.equal(next.ok, true); assert.equal(JSON.stringify(r), before); });
