import { test } from 'node:test';
import assert from 'node:assert/strict';
const module = await import('../src/local-connector.ts').catch(() => ({}));
const { LocalRelaySession, connectorSocketOptions } = module;
const request = (changes={}) => JSON.stringify({v:1,kind:'request',id:'operation-1',generation:3,deadlineAt:Date.now()+1000,headers:[['content-type','application/json']],bodyBase64:Buffer.from('{"jsonrpc":"2.0","id":1,"method":"ping"}').toString('base64'),...changes});
function setup(fetcher=async()=>new Response('{"ok":true}',{headers:{'content-type':'application/json'}})) {
  const sent=[], closed=[];
  const session = new LocalRelaySession({origin:'http://127.0.0.1:9999/mcp/', originHeaders:{'X-SLM-Install-Token':'local-test'}, fetcher, send:text=>sent.push(JSON.parse(text)), close:code=>closed.push(code)});
  return {session,sent,closed};
}
test('missing implementation is the explicit RED signal',()=>assert.equal(typeof LocalRelaySession,'function'));
test('ready handshake precedes origin execution',async()=>{let calls=0;const s=setup(async()=>{calls++;return new Response('');});await s.session.receive(request());assert.equal(calls,0);assert.equal(s.closed.length,1);});
test('request uses fixed loopback origin and private local header',async()=>{let observed;const s=setup(async(url,opts)=>{observed={url,opts};return new Response('result');});await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request());assert.equal(observed.url,'http://127.0.0.1:9999/mcp/');assert.equal(observed.opts.redirect,'error');assert.equal(observed.opts.headers.get('X-SLM-Install-Token'),'local-test');assert.equal(observed.opts.headers.has('Authorization'),false);assert.equal(s.sent[0].status,200);assert.equal(Buffer.from(s.sent[0].bodyBase64,'base64').toString(),'result');});
test('refuses remote, credential-bearing, query and non-MCP origins',()=>{for(const origin of ['http://example.com/mcp/','http://localhost/mcp/','http://u:p@127.0.0.1/mcp/','http://127.0.0.1/mcp/?url=x','http://127.0.0.1/admin'])assert.throws(()=>new LocalRelaySession({origin,originHeaders:{},send(){},close(){}}));});
test('stale generation cannot hit origin',async()=>{let calls=0;const s=setup(async()=>{calls++;return new Response('');});await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request({generation:2}));assert.equal(calls,0);assert.equal(s.closed.length,1);});
test('expired request is refused before local call',async()=>{let calls=0;const s=setup(async()=>{calls++;return new Response('');});await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request({deadlineAt:0}));assert.equal(calls,0);assert.equal(s.sent[0].status,504);});
test('origin failure is sanitized',async()=>{const s=setup(async()=>{throw Error('SECRET detail');});await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request());assert.equal(s.sent[0].status,502);assert.ok(!JSON.stringify(s.sent).includes('SECRET'));});
test('bodyless origin response is preserved',async()=>{const s=setup(async()=>new Response(null,{status:204}));await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request());assert.equal(s.sent[0].bodyBase64,'');assert.equal(s.sent[0].status,204);});
test('response body is capped while reading',async()=>{const s=setup(async()=>new Response(new Uint8Array(4194305)));await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive(request());assert.equal(s.sent[0].status,502);});
test('remote cancellation aborts local fetch and emits no success',async()=>{let signal,finish;const s=setup(async(_,opts)=>{signal=opts.signal;return new Promise(resolve=>{finish=resolve;});});await s.session.receive('{"v":1,"kind":"ready","generation":3}');const pending=s.session.receive(request());await s.session.receive(JSON.stringify({v:1,kind:'cancel',id:'operation-1',generation:3}));assert.equal(signal.aborted,true);finish(new Response('late'));await pending;assert.equal(s.sent.length,0);});
test('socket shutdown fences late responses',async()=>{let finish;const s=setup(async()=>new Promise(resolve=>{finish=resolve;}));await s.session.receive('{"v":1,"kind":"ready","generation":3}');const pending=s.session.receive(request());s.session.stop();finish(new Response('late'));await pending;assert.equal(s.sent.length,0);});
test('duplicate ready is a protocol violation',async()=>{const s=setup();await s.session.receive('{"v":1,"kind":"ready","generation":3}');await s.session.receive('{"v":1,"kind":"ready","generation":3}');assert.equal(s.closed.length,1);});
test('socket config binds device authorization to curated WSS endpoint',()=>{const opts=connectorSocketOptions('wss://connect.superlocalmemory.com/connector','a'.repeat(40));assert.equal(opts.url,'wss://connect.superlocalmemory.com/connector');assert.equal(opts.options.headers.Authorization,'Bearer '+ 'a'.repeat(40));assert.equal(opts.options.followRedirects,false);assert.equal(opts.options.perMessageDeflate,false);});
test('socket config rejects unapproved hosts and token URL leaks',()=>{for(const url of ['ws://connect.superlocalmemory.com/connector','wss://evil.com/connector','wss://connect.superlocalmemory.com/connector?token=x'])assert.throws(()=>connectorSocketOptions(url,'a'.repeat(40)));});
