import test from 'node:test';
import assert from 'node:assert/strict';
let api;try{api=await import('../src/mcp-http.ts');}catch{api=null;}
function message(method='tools/call',args={query:'synthetic'}){return {jsonrpc:'2.0',id:1,method,params:method==='tools/call'?{name:'recall',arguments:args}:{}};}
function request(body=message(),headers={}){return new Request('https://mcp.superlocalmemory.com/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream',...headers},body:typeof body==='string'?body:JSON.stringify(body)});}
function modern(){const body=message();body.params._meta={'io.modelcontextprotocol/protocolVersion':'2026-07-28'};return {body,headers:{'MCP-Protocol-Version':'2026-07-28','Mcp-Method':'tools/call','Mcp-Name':'recall'}};}
test('legacy request retains original bytes and body-derived method',async()=>{assert.ok(api);const body=' { "jsonrpc":"2.0", "id":1, "method":"tools/list" } ';const parsed=await api.parseMcpRequest(request(body));assert.equal(new TextDecoder().decode(parsed.envelope.originalBody),body);assert.equal(parsed.envelope.era,'legacy');assert.equal(parsed.envelope.rpcMethod,'tools/list');});
test('modern metadata matches headers without modifying original MCP body',async()=>{assert.ok(api);const {body,headers}=modern();const parsed=await api.parseMcpRequest(request(body,headers));assert.equal(parsed.envelope.era,'modern-2026-07-28');assert.equal(parsed.envelope.toolName,'recall');assert.deepEqual(parsed.envelope.arguments,{query:'synthetic'});});
for(const [name,body] of [['duplicate','{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"recall","name":"remember","arguments":{}}}'],['nested duplicate','{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"recall","arguments":{"profile_id":"a","profile_id":"b"}}}'],['batch',[message()]],['response',{jsonrpc:'2.0',id:1,result:{}}],['bad rpc version',{...message(),jsonrpc:'1.0'}],['bad id',{...message(),id:true}],['bad args',{...message(),params:{name:'recall',arguments:[]}}],['comments','{/* comment */"method":"tools/list"}'],['trailing comma','{"jsonrpc":"2.0","method":"tools/list",}']])test('reject '+name,async()=>{assert.ok(api);await assert.rejects(api.parseMcpRequest(request(body)));});
for(const header of ['Mcp-Method','Mcp-Name','MCP-Protocol-Version'])test('modern missing '+header+' is refused',async()=>{assert.ok(api);const {body,headers}=modern();delete headers[header];await assert.rejects(api.parseMcpRequest(request(body,headers)));});
test('header routing cannot claim recall while body asks remember',async()=>{assert.ok(api);const {body,headers}=modern();headers['Mcp-Name']='remember';await assert.rejects(api.parseMcpRequest(request(body,headers)));});
test('encoded standard name is compared to body after strict decoding',async()=>{assert.ok(api);const {body,headers}=modern();headers['Mcp-Name']='=?base64?'+btoa('recall')+'?=';assert.equal((await api.parseMcpRequest(request(body,headers))).envelope.toolName,'recall');});
test('curated parameter metadata must match schema path and body',async()=>{assert.ok(api);const {body,headers}=modern();body.params.arguments.profile_id='work';headers['Mcp-Param-profile']='work';const options={parameterHeaders:[{tool:'recall',header:'Mcp-Param-profile',path:['profile_id']}]};assert.deepEqual((await api.parseMcpRequest(request(body,headers),options)).parameterHeaderNames,['mcp-param-profile']);headers['Mcp-Param-profile']='other';await assert.rejects(api.parseMcpRequest(request(body,headers),options));});
test('provided annotated argument cannot omit its required metadata header',async()=>{assert.ok(api);const {body,headers}=modern();body.params.arguments.profile_id='work';await assert.rejects(api.parseMcpRequest(request(body,headers),{parameterHeaders:[{tool:'recall',header:'Mcp-Param-profile',path:['profile_id']}]}));});
test('request byte cap rejects oversized streaming body',async()=>{assert.ok(api);await assert.rejects(api.parseMcpRequest(request('x'.repeat(1024*1024+1))));});
test('tools/list is filtered to this grant and marked private',()=>{assert.ok(api);const body=JSON.stringify({jsonrpc:'2.0',id:1,result:{cacheScope:'public',ttlMs:60000,tools:[{name:'recall',inputSchema:{type:'object'}},{name:'remember',inputSchema:{}},{name:'switch_profile',inputSchema:{}}]}});const result=JSON.parse(api.filterMcpResponse(new TextEncoder().encode(body),{rpcMethod:'tools/list',rpcId:1},['recall']));assert.deepEqual(result.result.tools.map(x=>x.name),['recall']);assert.equal(result.result.cacheScope,'private');assert.equal(result.result.ttlMs,0);});
test('response correlation and malformed catalogs fail closed',()=>{assert.ok(api);for(const body of [{jsonrpc:'2.0',id:2,result:{}},{jsonrpc:'2.0',id:1,result:{tools:'all'}}])assert.throws(()=>api.filterMcpResponse(new TextEncoder().encode(JSON.stringify(body)),{rpcMethod:'tools/list',rpcId:1},['recall']));});

for(const name of ['x-slm-grant','X-SLM-Peer','x-slm-anything','X-Slm-'])test('client-sent '+name+' is refused before anything is forwarded',async()=>{assert.ok(api);await assert.rejects(api.parseMcpRequest(request(message(),{[name]:'forged'})),error=>error.code==='HEADER_MISMATCH'&&error.status===400&&error.rpcCode===-32020);});
test('other headers, including ones that only resemble the reserved prefix, are unaffected',async()=>{assert.ok(api);const parsed=await api.parseMcpRequest(request(message(),{'x-slm':'1','x-request-id':'a','user-agent':'x'}));assert.equal(parsed.envelope.toolName,'recall');assert.deepEqual(parsed.headers.map(h=>h[0]).sort(),['accept','content-type']);});
