import {env} from 'cloudflare:workers';
import {evictDurableObject} from 'cloudflare:test';
import {expect,test} from 'vitest';
import {generateKeyPair,exportJWK,calculateJwkThumbprint} from 'jose';
import {tokenHash} from '../../src/device-proof.ts';
import type {BootstrapBinding} from '../../src/bootstrap-do.ts';
import type {OwnedConnection} from '../../src/owner-index-do.ts';
async function rejected(operation:()=>Promise<unknown>,code:string){const pending=operation() as Promise<unknown>&{[Symbol.dispose]?:()=>void};try{await expect((async()=>{await pending;})()).rejects.toThrow(code);}finally{pending[Symbol.dispose]?.();}}
async function fixture(){
 const keys=await generateKeyPair('ES256');const jwk=await exportJWK(keys.publicKey);const jkt=await calculateJwkThumbprint(jwk);const verifier='v'.repeat(64);
 const binding:BootstrapBinding={connectionId:crypto.randomUUID().replaceAll('-',''),installationId:'install-a',profileId:'default',host:'muse',permissions:{read:true,write:false,correction:false,session:false},deviceJwk:jwk,expiresAtMs:Date.now()+600000,authRequest:{responseType:'code',clientId:'native-client',redirectUri:'http://127.0.0.1:8805/api/v3/connections/callback',scope:['slm:connect'],state:'s'.repeat(64),codeChallenge:await tokenHash(verifier),codeChallengeMethod:'S256',resource:'https://auth.superlocalmemory.com/owner',issuer:'https://auth.superlocalmemory.com'}};
 return {binding,jkt,verifier};
}
test('bootstrap PKCE binding is immutable and ownership confirmation survives restart',async()=>{const {binding}=await fixture();const stub=env.BOOTSTRAPS.getByName(crypto.randomUUID());await stub.configure(binding);await stub.configure(binding);await stub.approve('16027584');await stub.confirm('16027584','native-client');await evictDurableObject(stub);expect(await stub.get()).toMatchObject({status:'completed',ownerId:'16027584'});await rejected(()=>stub.configure({...binding,profileId:'other'}),'bootstrap_conflict');});
test('cancellation requires original verifier and is terminal',async()=>{const {binding,verifier}=await fixture();const stub=env.BOOTSTRAPS.getByName(crypto.randomUUID());await stub.configure(binding);await rejected(()=>stub.cancel('x'.repeat(64)),'invalid_bootstrap_proof');await stub.cancel(verifier);await rejected(()=>stub.approve('16027584'),'bootstrap_unavailable');await rejected(()=>stub.configure(binding),'bootstrap_cancelled');});
test('a foreign owner or native client cannot confirm another bootstrap',async()=>{const {binding}=await fixture();const stub=env.BOOTSTRAPS.getByName(crypto.randomUUID());await stub.configure(binding);await stub.approve('16027584');await rejected(()=>stub.approve('999'),'owner_mismatch');await rejected(()=>stub.confirm('16027584','other-client'),'bootstrap_unavailable');});
test('malformed bootstrap data is rejected with a bounded error',async()=>{const {binding}=await fixture();const stub=env.BOOTSTRAPS.getByName(crypto.randomUUID());await rejected(()=>stub.configure({...binding,authRequest:{...binding.authRequest,scope:null as never}}),'invalid_bootstrap');await rejected(()=>stub.configure({...binding,installationId:42 as never}),'invalid_bootstrap');});
test('owner index binds client and signing key without exposing operational credentials',async()=>{const {binding,jkt}=await fixture();const stub=env.OWNERS.getByName(crypto.randomUUID());await stub.bind('16027584','install-a','default','native-client',jkt);expect(await stub.authorizeNative('16027584','install-a','default','native-client',jkt)).toBe(true);expect(await stub.authorizeNative('16027584','install-a','other','native-client',jkt)).toBe(false);const row:OwnedConnection={connectionId:binding.connectionId,installationId:'install-a',profileId:'default',host:'muse',permissions:binding.permissions,credentialEnvelope:'encrypted-synthetic',deviceDigest:'a'.repeat(64),deviceJkt:jkt,deviceExpiresAtMs:Date.now()+60000,generation:1,revokedAt:null,cleanupPending:false};await stub.addConnection('16027584','install-a','default','native-client',row);const listed=await stub.list('16027584');expect(JSON.stringify(listed)).not.toContain('encrypted-synthetic');expect(await stub.list('999')).toEqual([]);await evictDurableObject(stub);expect(await stub.getConnection('16027584',row.connectionId)).toMatchObject(row);});
test('native key or client substitution cannot take over an owned installation',async()=>{const {jkt}=await fixture();const stub=env.OWNERS.getByName(crypto.randomUUID());await stub.bind('16027584','install-a','default','native-client',jkt);await rejected(()=>stub.bind('16027584','install-a','default','other-client',jkt),'native_binding_conflict');await rejected(()=>stub.bind('999','install-b','default','native-client',jkt),'owner_mismatch');});
test('owner revocation is versioned, durable and cleanup is explicitly separate',async()=>{const {binding,jkt}=await fixture();const stub=env.OWNERS.getByName(crypto.randomUUID());await stub.bind('16027584','install-a','default','native-client',jkt);const row:OwnedConnection={connectionId:binding.connectionId,installationId:'install-a',profileId:'default',host:'muse',permissions:binding.permissions,credentialEnvelope:'encrypted-synthetic',deviceDigest:'a'.repeat(64),deviceJkt:jkt,deviceExpiresAtMs:Date.now()+60000,generation:1,revokedAt:null,cleanupPending:false};await stub.addConnection('16027584','install-a','default','native-client',row);await rejected(()=>stub.revoke('16027584',row.connectionId,0),'version_conflict');const generation=await stub.revoke('16027584',row.connectionId,1);expect(generation).toBe(2);await evictDurableObject(stub);await rejected(()=>stub.addConnection('16027584','install-a','default','native-client',row),'connection_conflict');expect(await stub.markCleanup('16027584',row.connectionId,1)).toBe(false);expect(await stub.markCleanup('16027584',row.connectionId,2)).toBe(true);});

test('cancelled connection id cannot be created by delayed provisioning',async()=>{
 const ownerId='16027584';const connectionId=crypto.randomUUID().replaceAll('-','');const installation='i-'+connectionId;const profile='synthetic';const client='c-'+connectionId;const jkt='a'.repeat(43);
 const stub=env.OWNERS.getByName(ownerId);await stub.bind(ownerId,installation,profile,client,jkt);await stub.cancelConnection(ownerId,connectionId);
 await expect((async()=>{await stub.addConnection(ownerId,installation,profile,client,{connectionId,installationId:installation,profileId:profile,host:'muse',permissions:{read:true,write:false,correction:false,session:false},credentialEnvelope:'encrypted',deviceDigest:'a'.repeat(64),deviceJkt:jkt,deviceExpiresAtMs:Date.now()+60000,generation:1,revokedAt:null,cleanupPending:false});})()).rejects.toThrow('connection_cancelled');
 expect(await stub.getConnection(ownerId,connectionId)).toBeNull();
});

test('generic MCP client keeps the same native ownership and permission boundaries',async()=>{
 const {binding,jkt}=await fixture();binding.host='other_mcp';
 const bootstrap=env.BOOTSTRAPS.getByName(crypto.randomUUID());await bootstrap.configure(binding);await bootstrap.approve('16027584');await bootstrap.confirm('16027584','native-client');
 const owner=env.OWNERS.getByName(crypto.randomUUID());await owner.bind('16027584','install-a','default','native-client',jkt);
 const row:OwnedConnection={connectionId:binding.connectionId,installationId:'install-a',profileId:'default',host:'other_mcp',permissions:binding.permissions,credentialEnvelope:'encrypted-synthetic',deviceDigest:'a'.repeat(64),deviceJkt:jkt,deviceExpiresAtMs:Date.now()+60000,generation:1,revokedAt:null,cleanupPending:false};
 await owner.addConnection('16027584','install-a','default','native-client',row);expect(await owner.getConnection('16027584',row.connectionId)).toMatchObject({host:'other_mcp',permissions:binding.permissions});expect(await owner.list('999')).toEqual([]);
 const invalid=env.BOOTSTRAPS.getByName(crypto.randomUUID());await rejected(()=>invalid.configure({...binding,host:'https://evil.example'}),'invalid_bootstrap');
});
