import {env} from 'cloudflare:workers';
import {evictDurableObject} from 'cloudflare:test';
import {expect,test} from 'vitest';
import type {AuthorizationGrant,ConnectionGrant,VerifiedActor,RequestEnvelope} from '../../src/contracts.ts';

const connection:ConnectionGrant={connectionId:'connection-a',ownerId:'owner-a',installationId:'installation-a',profileId:'profile-a',exactAgentPath:'/mcp',upstreamUrl:'http://127.0.0.1:8765/mcp',originCredentialRef:'keychain:installation-a',allowedTools:['recall','remember','get_status'],allowCorrection:false,allowSharedRead:false,allowGlobalRead:false,policyVersion:1,revokedAt:null};
const grant:AuthorizationGrant={authorizationId:'authorization-a',audience:'https://mcp.superlocalmemory.com/mcp',ownerId:'owner-a',clientId:'client-a',connectionId:'connection-a',consentedTools:['recall','remember'],consentedScopes:['slm:read','slm:write'],consentedCorrection:false,consentedSharedRead:false,consentedGlobalRead:false,authorizationVersion:1,revokedAt:null};
const actor:VerifiedActor={ownerId:'owner-a',authorizationId:'authorization-a',connectionId:'connection-a',clientId:'client-a',audience:grant.audience,credentialKind:'oauth',scopes:['slm:read','slm:write']};
const request:RequestEnvelope={era:'legacy',rpcMethod:'tools/call',toolName:'recall',arguments:{query:'synthetic'},originalBody:new Uint8Array()};
async function setup(){const stub=env.REGISTRIES.getByName(crypto.randomUUID());await stub.configure(connection);await stub.addAuthorization(grant);await stub.setEntitlement('owner-a',Date.now()+60000,0);return stub;}

test('registry admits a current bound actor with the intersection of scopes',async()=>{const stub=await setup();const result=await stub.admit(actor,grant.audience,request);expect(result.allowed).toBe(true);if(result.allowed)expect(result.grant.allowedTools).toEqual(['recall','remember']);});
test('registry refuses unknown or cross-owner actor',async()=>{const stub=await setup();expect((await stub.admit({...actor,ownerId:'other'},grant.audience,request)).allowed).toBe(false);expect((await stub.admit({...actor,authorizationId:'other'},grant.audience,request)).allowed).toBe(false);});
test('registry defaults entitlement off and expires it independently of local core',async()=>{const stub=env.REGISTRIES.getByName(crypto.randomUUID());await stub.configure(connection);await stub.addAuthorization(grant);expect(await stub.admit(actor,grant.audience,request)).toMatchObject({allowed:false,code:'ENTITLEMENT_REQUIRED'});await stub.setEntitlement('owner-a',Date.now()-1,0);expect((await stub.admit(actor,grant.audience,request)).allowed).toBe(false);});
test('grant identity cannot be reused to widen consent',async()=>{const stub=await setup();await expect(stub.addAuthorization({...grant,consentedSharedRead:true})).rejects.toThrow('authorization_conflict');expect((await stub.admit(actor,grant.audience,request)).allowed).toBe(true);});
test('connection ownership and profile binding cannot be replaced',async()=>{const stub=await setup();await expect(stub.configure({...connection,profileId:'other'})).rejects.toThrow('connection_conflict');await expect(stub.configure({...connection,ownerId:'other'})).rejects.toThrow('connection_conflict');});
test('revoking authorization commits before acknowledgement and survives eviction',async()=>{const stub=await setup();expect(await stub.revokeAuthorization('owner-a','authorization-a',1)).toBe(2);await evictDurableObject(stub);expect(await stub.admit(actor,grant.audience,request)).toMatchObject({allowed:false,code:'REVOKED'});await expect(stub.addAuthorization(grant)).rejects.toThrow('authorization_conflict');});
test('revoking connection is terminal and survives restart',async()=>{const stub=await setup();expect(await stub.revokeConnection('owner-a',1)).toBe(2);await evictDurableObject(stub);expect((await stub.admit(actor,grant.audience,request)).allowed).toBe(false);await expect(stub.configure(connection)).rejects.toThrow('connection_revoked');});
test('revocation enforces owner and compare-and-swap version',async()=>{const stub=await setup();await expect(stub.revokeConnection('other',1)).rejects.toThrow('owner_mismatch');await expect(stub.revokeAuthorization('owner-a','authorization-a',0)).rejects.toThrow('version_conflict');expect((await stub.admit(actor,grant.audience,request)).allowed).toBe(true);});
test('token scopes and profile arguments are rechecked at admission',async()=>{const stub=await setup();expect((await stub.admit({...actor,scopes:['slm:read']},grant.audience,{...request,toolName:'remember',arguments:{content:'synthetic'}})).allowed).toBe(false);expect((await stub.admit(actor,grant.audience,{...request,arguments:{profile_id:'other'}})).allowed).toBe(false);});
test('concurrent immutable grants never admit a widened payload',async()=>{const stub=await setup();const results=await Promise.allSettled([stub.addAuthorization(grant),stub.addAuthorization({...grant,consentedCorrection:true})]);expect(results[0].status).toBe('fulfilled');expect(results[1].status).toBe('rejected');});
test('registry has no public administrative HTTP route',async()=>{const stub=await setup();expect((await stub.fetch(new Request('https://private.invalid/admin'))).status).toBe(404);});
test('malformed control-plane data is rejected before durable mutation',async()=>{const stub=env.REGISTRIES.getByName(crypto.randomUUID());await expect(stub.configure({...connection,policyVersion:0})).rejects.toThrow('invalid_connection');await expect(stub.configure({...connection,allowedTools:['admin']})).rejects.toThrow('invalid_connection');await stub.configure(connection);await expect(stub.addAuthorization({...grant,consentedScopes:['invalid'] as never})).rejects.toThrow('invalid_authorization');});
