#!/usr/bin/env node
/**
 * build-plugin.mjs — SLM plugin-src single-source build generator
 *
 * DOC-CORRECT layout (verified from official Claude Code plugin docs):
 *   .claude-plugin/marketplace.json   (repo root; source:"./plugin")
 *   plugin/                           (PLUGIN ROOT)
 *     .claude-plugin/plugin.json      (manifest ONLY here; version ONLY here)
 *     skills/<7>/SKILL.md
 *     agents/<2>.md
 *     .mcp.json                       (SLM_MCP_PROFILE=code)
 *     hooks/hooks.json
 *     scripts/ensure-venv.sh          (+x)
 *     settings.json · requirements.txt · CLAUDE.md
 *
 * Node >= 18. Zero external dependencies (only node:fs/path/crypto/process).
 * Exit codes: 0 = success/in-sync  1 = fatal error  2 = --check drift detected
 *
 * Usage:
 *   node scripts/build-plugin.mjs [--check] [--quiet] [--help]
 */

'use strict';

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import process from 'node:process';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const VERSION = '3.6.19';
const MANIFEST_REL = 'plugin-src/manifest.json';
const GENERATED_BANNER = `# _GENERATED — DO NOT HAND-EDIT

This directory is generated by \`scripts/build-plugin.mjs\` from \`plugin-src/\`.
Run \`npm run build:plugin\` to regenerate.
Run \`npm run check:plugin\` (or \`--check\`) in CI to verify in-sync.
Source of truth: \`plugin-src/skills/\`, \`plugin-src/manifest.json\`.
`;

const _SKIP_DIRS = new Set(['.backup', '.git', 'node_modules', 'build', 'venv', '__pycache__']);

// ---------------------------------------------------------------------------
// Pure utilities
// ---------------------------------------------------------------------------

/**
 * Normalize line endings to LF, ensure exactly one trailing newline.
 * @param {string} s
 * @returns {string}
 */
export function normalizeNewlines(s) {
  const normalized = s.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  return normalized.replace(/\n*$/, '\n');
}

/**
 * Stable JSON serializer (recursive sorted keys, 2-space indent, LF, trailing newline).
 * Prevents the array-replacer bug that silently drops nested keys.
 * @param {unknown} obj
 * @returns {string}
 */
export function stableStringify(obj) {
  function sort(val) {
    if (Array.isArray(val)) return val.map(sort);
    if (val !== null && typeof val === 'object') {
      const out = {};
      for (const k of Object.keys(val).sort()) {
        out[k] = sort(val[k]);
      }
      return out;
    }
    return val;
  }
  return JSON.stringify(sort(obj), null, 2) + '\n';
}

/**
 * Replace the frontmatter `version:` line with the given version string.
 * ONLY touches the YAML frontmatter block (between leading `---`).
 * Throws if no version line found in frontmatter.
 * @param {string} md
 * @param {string} ver
 * @returns {string}
 */
export function stampVersion(md, ver) {
  // Match frontmatter: opening ---, content, closing ---
  const fmMatch = md.match(/^(---\n)([\s\S]*?)(^---\n)/m);
  if (!fmMatch) {
    throw new Error('stampVersion: no YAML frontmatter found');
  }
  const [fullMatch, open, body, close] = fmMatch;
  if (!/^version:/m.test(body)) {
    throw new Error('stampVersion: no version: line in frontmatter');
  }
  const newBody = body.replace(/^version:.*$/m, `version: "${ver}"`);
  const newFm = open + newBody + close;
  return md.replace(fullMatch, newFm);
}

/**
 * OQ-2 attribution normalization — ANCHORED to attribution footer patterns only.
 * Does NOT rewrite prose like "API v2" or "the MIT license".
 *
 * Patterns fixed (in footer block):
 *   **Project:** SuperLocalMemory V2  =>  **Project:** SuperLocalMemory v3.6.14
 *   **License:** MIT (see ...)        =>  **License:** AGPL-3.0-or-later
 *   **Repository:** https://github.com/varun369/SuperLocalMemoryV2
 *     =>  **Repository:** https://github.com/qualixar/superlocalmemory
 *
 * Also fixes the corrupted L87 table row in slm-recall.
 * @param {string} md
 * @param {string} ver
 * @returns {string}
 */
function normalizeAttribution(md, ver) {
  let out = md;

  // Fix attribution footer lines (prefixed with **Project:**, **License:**, **Repository:**)
  // These are anchored to line-start with **...: patterns.
  out = out.replace(
    /^(\*\*Project:\*\*\s+SuperLocalMemory\s+)V2/mg,
    `$1v${ver}`
  );
  out = out.replace(
    /^(\*\*License:\*\*\s+)MIT(\s*\(see[^)]*\))?/mg,
    `$1AGPL-3.0-or-later`
  );
  out = out.replace(
    /^(\*\*Repository:\*\*\s+)https:\/\/github\.com\/varun369\/SuperLocalMemoryV2/mg,
    `$1https://github.com/qualixar/superlocalmemory`
  );

  // Fix corrupted L87 table row in slm-recall
  // Original: | `--min-score` | float | No | 0.3 | Minimum relevance (0.0-1-tags` | string | No | None | Filter by tags (comma-separated) |
  // Fix: split into two correct rows
  out = out.replace(
    /\| `--min-score` \| float \| No \| 0\.3 \| Minimum relevance \(0\.0-1-tags` \| string \| No \| None \| Filter by tags \(comma-separated\) \|/g,
    '| `--min-score` | float | No | 0.3 | Minimum relevance (0.0-1.0) |\n| `--tags` | string | No | None | Filter by tags (comma-separated) |'
  );

  return out;
}

/**
 * Full skill file rendering: normalizeNewlines → stampVersion → normalizeAttribution → normalizeNewlines.
 * Skills without a `version:` line in frontmatter are copied verbatim (no stamp).
 * @param {string} src raw source content
 * @param {string} ver version to stamp
 * @returns {string}
 */
export function renderSkillFile(src, ver) {
  let out = normalizeNewlines(src);
  // Only stamp if there is a version: line in frontmatter — new skills may not have one
  const fmMatch = out.match(/^(---\n)([\s\S]*?)(^---\n)/m);
  if (fmMatch && /^version:/m.test(fmMatch[2])) {
    out = stampVersion(out, ver);
  }
  out = normalizeAttribution(out, ver);
  out = normalizeNewlines(out);
  return out;
}

/**
 * Render plugin.json — full §5 schema. version ONLY here.
 * Paths are relative to the plugin root (= plugin/).
 * Uses stableStringify — no nested key dropping.
 * @param {object} manifest
 * @returns {string}
 */
export function renderPluginJson(manifest) {
  const obj = {
    author: {
      name: 'Qualixar',
      url: manifest.repository || 'https://github.com/qualixar/superlocalmemory',
    },
    description: manifest.marketplace.description,
    displayName: manifest.displayName || manifest.pluginName,
    hooks: './.mcp.json' === manifest.targets.plugin ? './hooks/hooks.json' : './hooks/hooks.json',
    keywords: manifest.keywords || [],
    mcpServers: './.mcp.json',
    name: manifest.pluginName,
    repository: manifest.repository || '',
    version: manifest.version,
  };
  // hooks pointer is always ./hooks/hooks.json relative to plugin root
  obj.hooks = './hooks/hooks.json';
  obj.mcpServers = './.mcp.json';
  return stableStringify(obj);
}

/**
 * Render marketplace.json — at repo root .claude-plugin/marketplace.json.
 * NO version key in plugin entry. source = "./plugin".
 * @param {object} manifest
 * @returns {string}
 */
export function renderMarketplaceJson(manifest) {
  const ownerObj = { name: 'Qualixar' };
  if (manifest.marketplace.ownerEmail) {
    ownerObj.email = manifest.marketplace.ownerEmail;
  }
  const obj = {
    name: 'qualixar',
    owner: ownerObj,
    plugins: [
      {
        author: { name: 'Qualixar' },
        description: manifest.marketplace.description,
        name: manifest.pluginName,
        source: './plugin',
      },
    ],
  };
  return stableStringify(obj);
}

// ---------------------------------------------------------------------------
// IO: loadManifest
// ---------------------------------------------------------------------------

/**
 * Load and validate plugin-src/manifest.json.
 * Throws (→ exit 1) on any IO or validation error.
 * @param {string} root repository root
 * @returns {object} parsed manifest
 */
export function loadManifest(root) {
  const p = path.join(root, MANIFEST_REL);
  let raw;
  try {
    raw = fs.readFileSync(p, 'utf8');
  } catch (err) {
    throw new Error(`loadManifest: cannot read ${p}: ${err.message}`);
  }

  let manifest;
  try {
    manifest = JSON.parse(raw);
  } catch (err) {
    throw new Error(`loadManifest: invalid JSON in ${p}: ${err.message}`);
  }

  // Validate required fields
  if (!manifest.version) throw new Error('loadManifest: manifest.version is required');
  if (!manifest.pluginName) throw new Error('loadManifest: manifest.pluginName is required');
  if (!Array.isArray(manifest.skills) || manifest.skills.length === 0) {
    throw new Error('loadManifest: manifest.skills must be a non-empty array');
  }
  if (!manifest.targets || typeof manifest.targets !== 'object') {
    throw new Error('loadManifest: manifest.targets must be an object');
  }
  if (!manifest.targets.plugin || typeof manifest.targets.plugin !== 'string') {
    throw new Error('loadManifest: manifest.targets.plugin is required and must be a string');
  }
  if (path.isAbsolute(manifest.targets.plugin)) {
    throw new Error('loadManifest: manifest.targets.plugin must be relative (absolute paths forbidden)');
  }

  return manifest;
}

// ---------------------------------------------------------------------------
// Core: derivePluginRoot — the plugin/ subdir from targets.plugin
// ---------------------------------------------------------------------------

/**
 * Derive the plugin root directory (plugin/) from manifest.targets.plugin.
 * targets.plugin = "plugin/.claude-plugin/plugin.json"
 * pluginRoot = path.resolve(root, "plugin")
 * @param {string} root
 * @param {object} manifest
 * @returns {string} absolute path to plugin root
 */
export function derivePluginRoot(root, manifest) {
  // targets.plugin = "plugin/.claude-plugin/plugin.json"
  // dirname twice: "plugin/.claude-plugin" -> "plugin"
  const pluginJsonRel = manifest.targets.plugin; // "plugin/.claude-plugin/plugin.json"
  const pluginClaudeDir = path.dirname(pluginJsonRel); // "plugin/.claude-plugin"
  const pluginRootRel = path.dirname(pluginClaudeDir); // "plugin"
  return path.resolve(root, pluginRootRel);
}

/**
 * Return the set of absolute managed root directories.
 * Now only manages plugin/ dir.
 * @param {string} root
 * @param {object} manifest
 * @returns {Set<string>}
 */
export function deriveManagedRoots(root, manifest) {
  const roots = new Set();
  roots.add(derivePluginRoot(root, manifest));
  return roots;
}

// ---------------------------------------------------------------------------
// Core: buildPlan — pure, returns Map<absPath, content>
// ---------------------------------------------------------------------------

/**
 * Build the full plan as a Map from absolute path to file content.
 * Pure: no IO side effects (reads plugin-src source files).
 * @param {string} root repository root
 * @param {object} manifest parsed manifest
 * @returns {Map<string, string>}
 */
export function buildPlan(root, manifest) {
  const plan = new Map();

  const pluginRoot = derivePluginRoot(root, manifest);
  const pluginClaudeDir = path.join(pluginRoot, '.claude-plugin');

  const sortedSkills = [...manifest.skills].sort((a, b) => a.name.localeCompare(b.name));

  // ---------------------------------------------------------------------------
  // Skills → plugin/skills/<name>/SKILL.md
  // ---------------------------------------------------------------------------
  for (const skill of sortedSkills) {
    const srcSkillDir = path.join(root, 'plugin-src', 'skills', skill.name);
    const srcSkillPath = path.join(srcSkillDir, 'SKILL.md');

    let srcContent;
    try {
      srcContent = fs.readFileSync(srcSkillPath, 'utf8');
    } catch (err) {
      throw new Error(`buildPlan: cannot read source skill ${srcSkillPath}: ${err.message}`);
    }

    const rendered = renderSkillFile(srcContent, manifest.version);
    plan.set(path.join(pluginRoot, 'skills', skill.name, 'SKILL.md'), rendered);

    // README verbatim (no stamp) if present
    if (skill.hasReadme) {
      const srcReadme = path.join(srcSkillDir, 'README.md');
      let readmeContent;
      try {
        readmeContent = fs.readFileSync(srcReadme, 'utf8');
      } catch (err) {
        throw new Error(`buildPlan: cannot read README ${srcReadme}: ${err.message}`);
      }
      plan.set(path.join(pluginRoot, 'skills', skill.name, 'README.md'), readmeContent);
    }
  }

  // ---------------------------------------------------------------------------
  // _GENERATED.md banner in plugin root
  // ---------------------------------------------------------------------------
  plan.set(path.join(pluginRoot, '_GENERATED.md'), GENERATED_BANNER);

  // ---------------------------------------------------------------------------
  // plugin/.claude-plugin/plugin.json
  // ---------------------------------------------------------------------------
  plan.set(path.join(pluginClaudeDir, 'plugin.json'), renderPluginJson(manifest));

  // ---------------------------------------------------------------------------
  // .claude-plugin/marketplace.json at REPO ROOT (not plugin root)
  // ---------------------------------------------------------------------------
  plan.set(path.join(root, '.claude-plugin', 'marketplace.json'), renderMarketplaceJson(manifest));

  // ---------------------------------------------------------------------------
  // Agents (verbatim, no commands/)
  // ---------------------------------------------------------------------------
  const agentsSrcPath = path.join(root, 'plugin-src', 'agents');
  if (fs.existsSync(agentsSrcPath)) {
    for (const fname of fs.readdirSync(agentsSrcPath)) {
      if (fname === '.gitkeep') continue;
      const srcFile = path.join(agentsSrcPath, fname);
      if (!fs.statSync(srcFile).isFile()) continue;
      const content = fs.readFileSync(srcFile, 'utf8');
      plan.set(path.join(pluginRoot, 'agents', fname), content);
    }
  }

  // ---------------------------------------------------------------------------
  // hooks: plugin/hooks/
  // ---------------------------------------------------------------------------
  const hooksPath = path.join(root, 'plugin-src', 'hooks');
  if (fs.existsSync(hooksPath)) {
    for (const fname of fs.readdirSync(hooksPath)) {
      if (fname === '.gitkeep') continue;
      const srcFile = path.join(hooksPath, fname);
      if (!fs.statSync(srcFile).isFile()) continue;
      const content = fs.readFileSync(srcFile, 'utf8');
      plan.set(path.join(pluginRoot, 'hooks', fname), content);
    }
  }

  // ---------------------------------------------------------------------------
  // Root-level plugin-src files → plugin/ (.mcp.json, settings.json, requirements.txt)
  // ---------------------------------------------------------------------------
  const rootFiles = ['.mcp.json', 'settings.json', 'requirements.txt'];
  for (const fname of rootFiles) {
    const srcFile = path.join(root, 'plugin-src', fname);
    if (fs.existsSync(srcFile)) {
      const content = fs.readFileSync(srcFile, 'utf8');
      plan.set(path.join(pluginRoot, fname), content);
    }
  }

  // ---------------------------------------------------------------------------
  // scripts/ → plugin/scripts/
  // ---------------------------------------------------------------------------
  const scriptsSrcPath = path.join(root, 'plugin-src', 'scripts');
  if (fs.existsSync(scriptsSrcPath)) {
    for (const fname of fs.readdirSync(scriptsSrcPath)) {
      if (fname === '.gitkeep') continue;
      const srcFile = path.join(scriptsSrcPath, fname);
      if (!fs.statSync(srcFile).isFile()) continue;
      const content = fs.readFileSync(srcFile, 'utf8');
      plan.set(path.join(pluginRoot, 'scripts', fname), content);
    }
  }

  // ---------------------------------------------------------------------------
  // CLAUDE.md from rules/CLAUDE.md.fragment → plugin/CLAUDE.md
  // ---------------------------------------------------------------------------
  const claudeFragmentPath = path.join(root, 'plugin-src', 'rules', 'CLAUDE.md.fragment');
  if (fs.existsSync(claudeFragmentPath)) {
    const fragmentContent = fs.readFileSync(claudeFragmentPath, 'utf8');
    plan.set(path.join(pluginRoot, 'CLAUDE.md'), fragmentContent);
  }

  return plan;
}

// ---------------------------------------------------------------------------
// Pure utility: _isExecutable — determines if a file should have +x bit set.
// Shell scripts (.sh) and extensionless launcher scripts (e.g. slm-launch)
// in scripts/ directories need the executable bit.
// ---------------------------------------------------------------------------

/**
 * Return true if the file at absPath should receive the executable (+x) bit.
 * Rules:
 *  - Any file ending in .sh
 *  - Any extensionless file inside a scripts/ directory (cross-platform launchers)
 * @param {string} absPath
 * @returns {boolean}
 */
function _isExecutable(absPath) {
  if (absPath.endsWith('.sh')) return true;
  // Extensionless files in a scripts/ directory (e.g. slm-launch)
  const base = path.basename(absPath);
  if (!base.includes('.') && absPath.includes(`${path.sep}scripts${path.sep}`)) {
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// IO: applyPlan — write-only-if-changed via sha256
// ---------------------------------------------------------------------------

/**
 * Apply the plan: write files only when content has changed (by sha256).
 * Creates parent directories as needed.
 * IMPORTANT: If the target path is a symlink, unlink it first before writing.
 * This prevents writes from propagating through symlinks to legacy source files.
 * @param {Map<string, string>} plan
 * @returns {number} number of files written
 */
export function applyPlan(plan) {
  let written = 0;
  for (const [absPath, content] of plan) {
    const newHash = sha256(content);
    let existingHash = null;

    // Check using lstat (not stat) to detect symlinks without following them
    if (fs.existsSync(absPath)) {
      const stat = fs.lstatSync(absPath);
      if (stat.isSymbolicLink()) {
        // Unlink the symlink before writing — prevents write-through to legacy source
        fs.unlinkSync(absPath);
        // existingHash stays null → will write
      } else {
        existingHash = sha256(fs.readFileSync(absPath, 'utf8'));
      }
    }

    if (existingHash !== newHash) {
      fs.mkdirSync(path.dirname(absPath), { recursive: true });
      fs.writeFileSync(absPath, content, 'utf8');
      // Preserve executable bit for shell scripts and extensionless launchers
      if (_isExecutable(absPath)) {
        const mode = fs.statSync(absPath).mode;
        fs.chmodSync(absPath, mode | 0o111);
      }
      written++;
    } else if (_isExecutable(absPath)) {
      // Ensure executable bit even if content unchanged
      const mode = fs.statSync(absPath).mode;
      if (!(mode & 0o100)) {
        fs.chmodSync(absPath, mode | 0o111);
      }
    }
  }
  return written;
}

function sha256(content) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

// ---------------------------------------------------------------------------
// IO: checkPlan — compare plan vs disk, return { stale, missing, extra }
// ---------------------------------------------------------------------------

/**
 * Compare plan against disk. Returns arrays of stale/missing/extra paths.
 * @param {Map<string, string>} plan
 * @param {string} root
 * @param {object} manifest
 * @returns {{ stale: string[], missing: string[], extra: string[] }}
 */
export function checkPlan(plan, root, manifest) {
  const stale = [];
  const missing = [];
  const extra = [];

  for (const [absPath, content] of plan) {
    if (!fs.existsSync(absPath)) {
      missing.push(absPath);
    } else {
      const disk = sha256(fs.readFileSync(absPath, 'utf8'));
      const expected = sha256(content);
      if (disk !== expected) stale.push(absPath);
    }
  }

  // Find extra files in managed roots (only plugin/)
  const managedRoots = deriveManagedRoots(root, manifest);
  for (const managedRoot of managedRoots) {
    if (!fs.existsSync(managedRoot)) continue;
    for (const absPath of walkDir(managedRoot)) {
      if (!plan.has(absPath)) {
        extra.push(absPath);
      }
    }
  }

  return { stale, missing, extra };
}

// ---------------------------------------------------------------------------
// IO: pruneOrphans — GUARDED: plan.size>0, path in managed root
// ---------------------------------------------------------------------------

/**
 * Remove files in managed roots that are NOT in the plan (orphan pruning).
 * Guards:
 *   1. plan.size > 0 (CRIT-1: refuse if plan empty)
 *   2. fullPath must be exactly managedRoot or start with managedRoot + sep (escape guard)
 *   3. Only files (not dirs) removed; dirs cleaned up if empty
 * @param {string} root
 * @param {Map<string, string>} plan
 * @param {Set<string>} managedRoots
 */
export function pruneOrphans(root, plan, managedRoots) {
  // CRIT-1: refuse if plan is empty
  if (plan.size === 0) {
    throw new Error('pruneOrphans: refusing to prune — plan is empty (safety guard)');
  }

  for (const managedRoot of managedRoots) {
    if (!fs.existsSync(managedRoot)) continue;
    for (const absPath of walkDir(managedRoot)) {
      // Escape guard: path must be within managedRoot
      if (
        absPath !== managedRoot &&
        !absPath.startsWith(managedRoot + path.sep)
      ) {
        throw new Error(
          `pruneOrphans: escape guard — ${absPath} is not under ${managedRoot}`
        );
      }

      if (!plan.has(absPath)) {
        fs.unlinkSync(absPath);
        // Remove empty parent dirs (up to managedRoot)
        cleanEmptyDirs(path.dirname(absPath), managedRoot);
      }
    }
  }
}

/**
 * Walk a directory recursively, skipping _SKIP_DIRS.
 * Yields absolute paths of FILES only.
 * @param {string} dir
 * @returns {Generator<string>}
 */
export function* walkDir(dir) {
  if (!fs.existsSync(dir)) return;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (_SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkDir(full);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

function cleanEmptyDirs(dir, stopAt) {
  if (dir === stopAt || !dir.startsWith(stopAt + path.sep)) return;
  try {
    const entries = fs.readdirSync(dir);
    if (entries.length === 0) {
      fs.rmdirSync(dir);
      cleanEmptyDirs(path.dirname(dir), stopAt);
    }
  } catch {
    // ignore — dir may not exist
  }
}

// ---------------------------------------------------------------------------
// IO: listTargetFiles — for --check extra detection
// ---------------------------------------------------------------------------

/**
 * List all files in managed roots.
 * @param {string} root
 * @param {object} manifest
 * @returns {string[]}
 */
export function listTargetFiles(root, manifest) {
  const result = [];
  for (const managedRoot of deriveManagedRoots(root, manifest)) {
    for (const f of walkDir(managedRoot)) {
      result.push(f);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// CLI: main
// ---------------------------------------------------------------------------

/**
 * Main entry point.
 * @param {string[]} argv
 */
export function main(argv) {
  const args = argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Usage: node scripts/build-plugin.mjs [options]

Options:
  --check              Check if generated files are in-sync (exit 2 if not)
  --quiet              Suppress non-error output
  --help, -h           Show this help

Output topology:
  .claude-plugin/marketplace.json   (repo root; source:"./plugin")
  plugin/                           (plugin root)
    .claude-plugin/plugin.json      (manifest; version only here)
    skills/<7>/SKILL.md
    agents/*.md
    .mcp.json  hooks/  scripts/  settings.json  requirements.txt  CLAUDE.md

Exit codes: 0=success/in-sync  1=fatal  2=check-drift
`.trimStart());
    process.exit(0);
  }

  const isCheck = args.includes('--check');
  const isQuiet = args.includes('--quiet');

  const root = process.cwd();

  let manifest;
  try {
    manifest = loadManifest(root);
  } catch (err) {
    console.error(`build-plugin: ${err.message}`);
    process.exit(1);
  }

  let plan;
  try {
    plan = buildPlan(root, manifest);
  } catch (err) {
    console.error(`build-plugin: ${err.message}`);
    process.exit(1);
  }

  if (isCheck) {
    // Never prune in --check mode
    const { stale, missing, extra } = checkPlan(plan, root, manifest);
    if (stale.length > 0 || missing.length > 0 || extra.length > 0) {
      if (!isQuiet) {
        if (stale.length) console.log('STALE:\n' + stale.map(f => `  ${f}`).join('\n'));
        if (missing.length) console.log('MISSING:\n' + missing.map(f => `  ${f}`).join('\n'));
        if (extra.length) console.log('EXTRA:\n' + extra.map(f => `  ${f}`).join('\n'));
      }
      process.exit(2);
    }
    if (!isQuiet) console.log('build-plugin --check: in-sync');
    process.exit(0);
  }

  // Build mode
  let written;
  try {
    written = applyPlan(plan);
  } catch (err) {
    console.error(`build-plugin: applyPlan failed: ${err.message}`);
    process.exit(1);
  }

  // Prune orphans in plugin/ (CRIT-1: guarded inside pruneOrphans)
  try {
    const managedRoots = deriveManagedRoots(root, manifest);
    pruneOrphans(root, plan, managedRoots);
  } catch (err) {
    console.error(`build-plugin: pruneOrphans failed: ${err.message}`);
    process.exit(1);
  }

  if (!isQuiet) {
    console.log(`build-plugin: done (${written} file(s) written)`);
  }
  process.exit(0);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
// Check if this is the main module (ESM way)
const isMain = process.argv[1] === new URL(import.meta.url).pathname;
if (isMain) {
  main(process.argv);
}
