#!/usr/bin/env node
/**
 * build-plugin.js — WP-04 SLM plugin-src single-source build generator
 *
 * Node >= 18. Zero external dependencies (only node:fs/path/crypto/process).
 * Exit codes: 0 = success/in-sync  1 = fatal error  2 = --check drift detected
 *
 * Usage:
 *   node scripts/build-plugin.js [--check] [--target ide|pkg|plugin|marketplace|all] [--quiet] [--help]
 */

'use strict';

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import process from 'node:process';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const VERSION = '3.6.14';
const MANIFEST_REL = 'plugin-src/manifest.json';
const GENERATED_BANNER = `# _GENERATED — DO NOT HAND-EDIT

This directory is generated by \`scripts/build-plugin.js\` from \`plugin-src/\`.
Run \`npm run build:plugin\` to regenerate.
Run \`npm run check:plugin\` (or \`--check\`) in CI to verify in-sync.
Source of truth: \`plugin-src/skills/\`, \`plugin-src/manifest.json\`.
`;

const _SKIP_DIRS = new Set(['.backup', '.git', 'node_modules', 'build', 'venv', '__pycache__']);

// ---------------------------------------------------------------------------
// Pure utilities
// ---------------------------------------------------------------------------

/**
 * Normalize line endings to LF, ensure exactly one trailing newline.
 * @param {string} s
 * @returns {string}
 */
export function normalizeNewlines(s) {
  const normalized = s.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  return normalized.replace(/\n*$/, '\n');
}

/**
 * Stable JSON serializer (recursive sorted keys, 2-space indent, LF, trailing newline).
 * Prevents the array-replacer bug that silently drops nested keys.
 * @param {unknown} obj
 * @returns {string}
 */
export function stableStringify(obj) {
  function sort(val) {
    if (Array.isArray(val)) return val.map(sort);
    if (val !== null && typeof val === 'object') {
      const out = {};
      for (const k of Object.keys(val).sort()) {
        out[k] = sort(val[k]);
      }
      return out;
    }
    return val;
  }
  return JSON.stringify(sort(obj), null, 2) + '\n';
}

/**
 * Replace the frontmatter `version:` line with the given version string.
 * ONLY touches the YAML frontmatter block (between leading `---`).
 * Throws if no version line found in frontmatter.
 * @param {string} md
 * @param {string} ver
 * @returns {string}
 */
export function stampVersion(md, ver) {
  // Match frontmatter: opening ---, content, closing ---
  const fmMatch = md.match(/^(---\n)([\s\S]*?)(^---\n)/m);
  if (!fmMatch) {
    throw new Error('stampVersion: no YAML frontmatter found');
  }
  const [fullMatch, open, body, close] = fmMatch;
  if (!/^version:/m.test(body)) {
    throw new Error('stampVersion: no version: line in frontmatter');
  }
  const newBody = body.replace(/^version:.*$/m, `version: "${ver}"`);
  const newFm = open + newBody + close;
  return md.replace(fullMatch, newFm);
}

/**
 * OQ-2 attribution normalization — ANCHORED to attribution footer patterns only.
 * Does NOT rewrite prose like "API v2" or "the MIT license".
 *
 * Patterns fixed (in footer block):
 *   **Project:** SuperLocalMemory V2  =>  **Project:** SuperLocalMemory v3.6.14
 *   **License:** MIT (see ...)        =>  **License:** AGPL-3.0-or-later
 *   **Repository:** https://github.com/varun369/SuperLocalMemoryV2
 *     =>  **Repository:** https://github.com/qualixar/superlocalmemory
 *
 * Also fixes the corrupted L87 table row in slm-recall.
 * @param {string} md
 * @param {string} ver
 * @returns {string}
 */
function normalizeAttribution(md, ver) {
  let out = md;

  // Fix attribution footer lines (prefixed with **Project:**, **License:**, **Repository:**)
  // These are anchored to line-start with **...: patterns.
  out = out.replace(
    /^(\*\*Project:\*\*\s+SuperLocalMemory\s+)V2/mg,
    `$1v${ver}`
  );
  out = out.replace(
    /^(\*\*License:\*\*\s+)MIT(\s*\(see[^)]*\))?/mg,
    `$1AGPL-3.0-or-later`
  );
  out = out.replace(
    /^(\*\*Repository:\*\*\s+)https:\/\/github\.com\/varun369\/SuperLocalMemoryV2/mg,
    `$1https://github.com/qualixar/superlocalmemory`
  );

  // Fix corrupted L87 table row in slm-recall
  // Original: | `--min-score` | float | No | 0.3 | Minimum relevance (0.0-1-tags` | string | No | None | Filter by tags (comma-separated) |
  // Fix: split into two correct rows
  out = out.replace(
    /\| `--min-score` \| float \| No \| 0\.3 \| Minimum relevance \(0\.0-1-tags` \| string \| No \| None \| Filter by tags \(comma-separated\) \|/g,
    '| `--min-score` | float | No | 0.3 | Minimum relevance (0.0-1.0) |\n| `--tags` | string | No | None | Filter by tags (comma-separated) |'
  );

  return out;
}

/**
 * Full skill file rendering: normalizeNewlines → stampVersion → normalizeAttribution → normalizeNewlines.
 * @param {string} src raw source content
 * @param {string} ver version to stamp
 * @returns {string}
 */
export function renderSkillFile(src, ver) {
  let out = normalizeNewlines(src);
  out = stampVersion(out, ver);
  out = normalizeAttribution(out, ver);
  out = normalizeNewlines(out);
  return out;
}

/**
 * Render plugin.json (minimal WP-04, WP-06 extends).
 * Uses stableStringify — no nested key dropping.
 * @param {object} manifest
 * @returns {string}
 */
export function renderPluginJson(manifest) {
  const obj = {
    author: {
      name: 'Varun Pratap Bhardwaj',
      url: 'https://github.com/qualixar',
    },
    description: manifest.marketplace.description,
    name: manifest.pluginName,
    version: manifest.version,
  };
  return stableStringify(obj);
}

/**
 * Render marketplace.json (minimal WP-04).
 * @param {object} manifest
 * @returns {string}
 */
export function renderMarketplaceJson(manifest) {
  const obj = {
    name: manifest.pluginName,
    owner: {
      name: manifest.marketplace.owner,
    },
    plugins: [
      {
        description: manifest.marketplace.description,
        name: manifest.pluginName,
        source: './',
        version: manifest.version,
      },
    ],
  };
  return stableStringify(obj);
}

// ---------------------------------------------------------------------------
// IO: loadManifest
// ---------------------------------------------------------------------------

/**
 * Load and validate plugin-src/manifest.json.
 * Throws (→ exit 1) on any IO or validation error.
 * @param {string} root repository root
 * @returns {object} parsed manifest
 */
export function loadManifest(root) {
  const p = path.join(root, MANIFEST_REL);
  let raw;
  try {
    raw = fs.readFileSync(p, 'utf8');
  } catch (err) {
    throw new Error(`loadManifest: cannot read ${p}: ${err.message}`);
  }

  let manifest;
  try {
    manifest = JSON.parse(raw);
  } catch (err) {
    throw new Error(`loadManifest: invalid JSON in ${p}: ${err.message}`);
  }

  // Validate required fields
  if (!manifest.version) throw new Error('loadManifest: manifest.version is required');
  if (!manifest.pluginName) throw new Error('loadManifest: manifest.pluginName is required');
  if (!Array.isArray(manifest.skills) || manifest.skills.length === 0) {
    throw new Error('loadManifest: manifest.skills must be a non-empty array');
  }
  if (!manifest.targets || typeof manifest.targets !== 'object') {
    throw new Error('loadManifest: manifest.targets must be an object');
  }

  // Validate targets: each value must be non-empty and NOT absolute (else repo root catastrophe)
  for (const [key, val] of Object.entries(manifest.targets)) {
    if (typeof val !== 'string' || val.trim() === '') {
      throw new Error(`loadManifest: manifest.targets.${key} must be a non-empty string`);
    }
    if (path.isAbsolute(val)) {
      throw new Error(
        `loadManifest: manifest.targets.${key} must be relative (absolute paths forbidden)`
      );
    }
  }

  return manifest;
}

// ---------------------------------------------------------------------------
// Core: deriveManagedRoots — RESPECTS --target
// ---------------------------------------------------------------------------

/**
 * Return the set of absolute managed root directories for the given target.
 * Prune ONLY iterates these. This prevents BUG-1 (cross-target deletion).
 * @param {string} root
 * @param {object} manifest
 * @param {string} target
 * @returns {Set<string>}
 */
export function deriveManagedRoots(root, manifest, target) {
  const roots = new Set();
  const addRoot = (rel) => roots.add(path.resolve(root, rel));

  if (target === 'ide' || target === 'all') {
    addRoot(manifest.targets.ide);
  }
  if (target === 'pkg' || target === 'all') {
    addRoot(manifest.targets.pkg);
  }
  if (target === 'plugin' || target === 'marketplace' || target === 'all') {
    addRoot(path.join(path.dirname(manifest.targets.plugin), 'skills'));
    // For plugin target, the skills subdir IS manifest.targets.plugin
    // Use manifest.targets.plugin directly since it already points to .claude-plugin/skills
    roots.delete(path.resolve(root, path.join(path.dirname(manifest.targets.plugin), 'skills')));
    addRoot(manifest.targets.plugin);
  }

  return roots;
}

// ---------------------------------------------------------------------------
// Core: buildPlan — pure, returns Map<absPath, content>
// ---------------------------------------------------------------------------

/**
 * Build the full plan as a Map from absolute path to file content.
 * Pure: no IO side effects.
 * @param {string} root repository root
 * @param {object} manifest parsed manifest
 * @param {string} target 'ide'|'pkg'|'plugin'|'marketplace'|'all'
 * @returns {Map<string, string>}
 */
export function buildPlan(root, manifest, target) {
  const plan = new Map();

  const sortedSkills = [...manifest.skills].sort((a, b) => a.name.localeCompare(b.name));

  // Determine which targets to include
  const doIde = target === 'ide' || target === 'all';
  const doPkg = target === 'pkg' || target === 'all';
  const doPlugin = target === 'plugin' || target === 'marketplace' || target === 'all';

  // ---------------------------------------------------------------------------
  // Skills
  // ---------------------------------------------------------------------------
  for (const skill of sortedSkills) {
    const srcSkillDir = path.join(root, 'plugin-src', 'skills', skill.name);
    const srcSkillPath = path.join(srcSkillDir, 'SKILL.md');

    let srcContent;
    try {
      srcContent = fs.readFileSync(srcSkillPath, 'utf8');
    } catch (err) {
      throw new Error(`buildPlan: cannot read source skill ${srcSkillPath}: ${err.message}`);
    }

    const rendered = renderSkillFile(srcContent, manifest.version);

    if (doIde) {
      plan.set(path.join(root, manifest.targets.ide, skill.name, 'SKILL.md'), rendered);
    }
    if (doPkg) {
      plan.set(path.join(root, manifest.targets.pkg, skill.name, 'SKILL.md'), rendered);
    }
    if (doPlugin) {
      plan.set(path.join(root, manifest.targets.plugin, skill.name, 'SKILL.md'), rendered);
    }

    // README verbatim (no stamp)
    if (skill.hasReadme) {
      const srcReadme = path.join(srcSkillDir, 'README.md');
      let readmeContent;
      try {
        readmeContent = fs.readFileSync(srcReadme, 'utf8');
      } catch (err) {
        throw new Error(`buildPlan: cannot read README ${srcReadme}: ${err.message}`);
      }
      if (doIde) {
        plan.set(path.join(root, manifest.targets.ide, skill.name, 'README.md'), readmeContent);
      }
      if (doPkg) {
        plan.set(path.join(root, manifest.targets.pkg, skill.name, 'README.md'), readmeContent);
      }
      if (doPlugin) {
        plan.set(
          path.join(root, manifest.targets.plugin, skill.name, 'README.md'),
          readmeContent
        );
      }
    }
  }

  // ---------------------------------------------------------------------------
  // _GENERATED.md banners — one per managed root (CRIT-2: in-plan for --check)
  // ---------------------------------------------------------------------------
  const managedRoots = deriveManagedRoots(root, manifest, target);
  for (const managedRoot of managedRoots) {
    plan.set(path.join(managedRoot, '_GENERATED.md'), GENERATED_BANNER);
  }

  // ---------------------------------------------------------------------------
  // JSON outputs (plugin + marketplace targets)
  // ---------------------------------------------------------------------------
  if (doPlugin) {
    const pluginRoot = path.resolve(root, path.dirname(manifest.targets.plugin));
    plan.set(path.join(pluginRoot, 'plugin.json'), renderPluginJson(manifest));
    plan.set(path.join(pluginRoot, 'marketplace.json'), renderMarketplaceJson(manifest));

    // Copy WP-05 agents, commands, rules (skip .gitkeep) verbatim
    const wp05Sources = ['agents', 'commands', 'rules'];
    for (const srcDir of wp05Sources) {
      const srcPath = path.join(root, 'plugin-src', srcDir);
      if (!fs.existsSync(srcPath)) continue;
      for (const fname of fs.readdirSync(srcPath)) {
        if (fname === '.gitkeep') continue;
        const srcFile = path.join(srcPath, fname);
        if (!fs.statSync(srcFile).isFile()) continue;
        const content = fs.readFileSync(srcFile, 'utf8');
        plan.set(path.join(pluginRoot, srcDir, fname), content);
      }
    }

    // hooks: copy non-.gitkeep files if any (hooks dir may only have .gitkeep)
    const hooksPath = path.join(root, 'plugin-src', 'hooks');
    if (fs.existsSync(hooksPath)) {
      for (const fname of fs.readdirSync(hooksPath)) {
        if (fname === '.gitkeep') continue;
        const srcFile = path.join(hooksPath, fname);
        if (!fs.statSync(srcFile).isFile()) continue;
        const content = fs.readFileSync(srcFile, 'utf8');
        plan.set(path.join(pluginRoot, 'hooks', fname), content);
      }
    }
  }

  return plan;
}

// ---------------------------------------------------------------------------
// IO: applyPlan — write-only-if-changed via sha256
// ---------------------------------------------------------------------------

/**
 * Apply the plan: write files only when content has changed (by sha256).
 * Creates parent directories as needed.
 * IMPORTANT: If the target path is a symlink, unlink it first before writing.
 * This prevents writes from propagating through symlinks to legacy source files
 * (e.g., ide/skills/slm-optimize/SKILL.md → skills/slm-optimize/SKILL.md).
 * @param {Map<string, string>} plan
 * @returns {number} number of files written
 */
export function applyPlan(plan) {
  let written = 0;
  for (const [absPath, content] of plan) {
    const newHash = sha256(content);
    let existingHash = null;

    // Check using lstat (not stat) to detect symlinks without following them
    if (fs.existsSync(absPath)) {
      const stat = fs.lstatSync(absPath);
      if (stat.isSymbolicLink()) {
        // Unlink the symlink before writing — prevents write-through to legacy source
        fs.unlinkSync(absPath);
        // existingHash stays null → will write
      } else {
        existingHash = sha256(fs.readFileSync(absPath, 'utf8'));
      }
    }

    if (existingHash !== newHash) {
      fs.mkdirSync(path.dirname(absPath), { recursive: true });
      fs.writeFileSync(absPath, content, 'utf8');
      written++;
    }
  }
  return written;
}

function sha256(content) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

// ---------------------------------------------------------------------------
// IO: checkPlan — compare plan vs disk, return { stale, missing, extra }
// ---------------------------------------------------------------------------

/**
 * Compare plan against disk. Returns arrays of stale/missing/extra paths.
 * @param {Map<string, string>} plan
 * @param {string} root
 * @param {object} manifest
 * @param {string} target
 * @returns {{ stale: string[], missing: string[], extra: string[] }}
 */
export function checkPlan(plan, root, manifest, target) {
  const stale = [];
  const missing = [];
  const extra = [];

  for (const [absPath, content] of plan) {
    if (!fs.existsSync(absPath)) {
      missing.push(absPath);
    } else {
      const disk = sha256(fs.readFileSync(absPath, 'utf8'));
      const expected = sha256(content);
      if (disk !== expected) stale.push(absPath);
    }
  }

  // Find extra files in managed roots
  const managedRoots = deriveManagedRoots(root, manifest, target);
  for (const managedRoot of managedRoots) {
    if (!fs.existsSync(managedRoot)) continue;
    for (const absPath of walkDir(managedRoot)) {
      if (!plan.has(absPath)) {
        extra.push(absPath);
      }
    }
  }

  return { stale, missing, extra };
}

// ---------------------------------------------------------------------------
// IO: pruneOrphans — GUARDED: plan.size>0, path in managed root, not in --check
// ---------------------------------------------------------------------------

/**
 * Remove files in managed roots that are NOT in the plan (orphan pruning).
 * Guards:
 *   1. plan.size > 0 (CRIT-1: refuse if plan empty)
 *   2. fullPath must be exactly managedRoot or start with managedRoot + sep (escape guard)
 *   3. Only files (not dirs) removed; dirs cleaned up if empty
 * @param {string} root
 * @param {Map<string, string>} plan
 * @param {Set<string>} managedRoots
 */
export function pruneOrphans(root, plan, managedRoots) {
  // CRIT-1: refuse if plan is empty
  if (plan.size === 0) {
    throw new Error('pruneOrphans: refusing to prune — plan is empty (safety guard)');
  }

  for (const managedRoot of managedRoots) {
    if (!fs.existsSync(managedRoot)) continue;
    for (const absPath of walkDir(managedRoot)) {
      // Escape guard: path must be within managedRoot
      if (
        absPath !== managedRoot &&
        !absPath.startsWith(managedRoot + path.sep)
      ) {
        throw new Error(
          `pruneOrphans: escape guard — ${absPath} is not under ${managedRoot}`
        );
      }

      if (!plan.has(absPath)) {
        fs.unlinkSync(absPath);
        // Remove empty parent dirs (up to managedRoot)
        cleanEmptyDirs(path.dirname(absPath), managedRoot);
      }
    }
  }
}

/**
 * Walk a directory recursively, skipping _SKIP_DIRS.
 * Yields absolute paths of FILES only.
 * @param {string} dir
 * @returns {Generator<string>}
 */
export function* walkDir(dir) {
  if (!fs.existsSync(dir)) return;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (_SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkDir(full);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

function cleanEmptyDirs(dir, stopAt) {
  if (dir === stopAt || !dir.startsWith(stopAt + path.sep)) return;
  try {
    const entries = fs.readdirSync(dir);
    if (entries.length === 0) {
      fs.rmdirSync(dir);
      cleanEmptyDirs(path.dirname(dir), stopAt);
    }
  } catch {
    // ignore — dir may not exist
  }
}

// ---------------------------------------------------------------------------
// IO: listTargetFiles — for --check extra detection
// ---------------------------------------------------------------------------

/**
 * List all files in managed roots (not in plan).
 * @param {string} root
 * @param {object} manifest
 * @param {string} target
 * @returns {string[]}
 */
export function listTargetFiles(root, manifest, target) {
  const result = [];
  for (const managedRoot of deriveManagedRoots(root, manifest, target)) {
    for (const f of walkDir(managedRoot)) {
      result.push(f);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// CLI: main
// ---------------------------------------------------------------------------

/**
 * Main entry point.
 * @param {string[]} argv
 */
export function main(argv) {
  const args = argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Usage: node scripts/build-plugin.js [options]

Options:
  --check              Check if generated files are in-sync (exit 2 if not)
  --target <t>         ide|pkg|plugin|marketplace|all (default: all)
  --quiet              Suppress non-error output
  --help, -h           Show this help

Exit codes: 0=success/in-sync  1=fatal  2=check-drift
`.trimStart());
    process.exit(0);
  }

  const isCheck = args.includes('--check');
  const isQuiet = args.includes('--quiet');
  const targetIdx = args.indexOf('--target');
  const target = targetIdx >= 0 ? args[targetIdx + 1] : 'all';

  const validTargets = new Set(['ide', 'pkg', 'plugin', 'marketplace', 'all']);
  if (!validTargets.has(target)) {
    console.error(`build-plugin: unknown target "${target}". Use: ${[...validTargets].join('|')}`);
    process.exit(1);
  }

  const root = process.cwd();

  let manifest;
  try {
    manifest = loadManifest(root);
  } catch (err) {
    console.error(`build-plugin: ${err.message}`);
    process.exit(1);
  }

  let plan;
  try {
    plan = buildPlan(root, manifest, target);
  } catch (err) {
    console.error(`build-plugin: ${err.message}`);
    process.exit(1);
  }

  if (isCheck) {
    // Never prune in --check mode
    const { stale, missing, extra } = checkPlan(plan, root, manifest, target);
    if (stale.length > 0 || missing.length > 0 || extra.length > 0) {
      if (!isQuiet) {
        if (stale.length) console.log('STALE:\n' + stale.map(f => `  ${f}`).join('\n'));
        if (missing.length) console.log('MISSING:\n' + missing.map(f => `  ${f}`).join('\n'));
        if (extra.length) console.log('EXTRA:\n' + extra.map(f => `  ${f}`).join('\n'));
      }
      process.exit(2);
    }
    if (!isQuiet) console.log('build-plugin --check: in-sync');
    process.exit(0);
  }

  // Build mode
  let written;
  try {
    written = applyPlan(plan);
  } catch (err) {
    console.error(`build-plugin: applyPlan failed: ${err.message}`);
    process.exit(1);
  }

  // Prune orphans (CRIT-1: guarded inside pruneOrphans)
  try {
    const managedRoots = deriveManagedRoots(root, manifest, target);
    pruneOrphans(root, plan, managedRoots);
  } catch (err) {
    console.error(`build-plugin: pruneOrphans failed: ${err.message}`);
    process.exit(1);
  }

  if (!isQuiet) {
    console.log(`build-plugin: done (${written} file(s) written, target=${target})`);
  }
  process.exit(0);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
// Check if this is the main module (ESM way)
const isMain = process.argv[1] === new URL(import.meta.url).pathname;
if (isMain) {
  main(process.argv);
}
